# Generated by Django 3.2.9 on 2021-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0002_auto_20211126_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(default=0, verbose_name='user_id')),
                ('project_id', models.IntegerField(default=0, verbose_name='project_id')),
                ('permission', models.CharField(choices=[('All', 'All'), ('Read_Only', 'Read_Only')], max_length=10)),
                ('role', models.CharField(max_length=255, verbose_name='role')),
            ],
        ),
    ]
