# Generated by Django 3.2.9 on 2021-12-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracking_system', '0003_contributors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='issue_tracking_system.projects', verbose_name='project_contributor'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_contributor'),
        ),
    ]
